title: All About Me 
author: Srinidhi Ayalasomayajula
email: sayalasomayajula@ebnet.org
description: 
  The purpose of this is for you to learn more about me

facebook_username: Srinidhi Ayala

theme: minima 
